/// Stateless calculation engine for the TimberGuard premium estimator.
///
/// Formula:
///   monthly = (equipmentValue x BASE_RATE / 12) x (1 - fireDiscount?)
///
/// Equipment older than [maxAgeYears] cannot be auto-quoted and returns null
/// to signal that the UI should display a "Contact Agent" prompt instead.
class PremiumCalculator {
  // Annual base rate: 2% of declared equipment value.
  static const double baseRate = 0.02;

  // Discount applied when an integrated fire suppression system is present.
  static const double fireSuppressDiscount = 0.15;

  // Equipment at or below this age qualifies for an instant estimate.
  static const int maxAgeYears = 20;

  /// Returns the estimated monthly premium in USD, or `null` when the
  /// equipment age exceeds [maxAgeYears] and requires a custom agent quote.
  static double? calculateMonthlyPremium({
    required double equipmentValue,
    required int equipmentAge,
    required bool hasFireSuppression
  }) {
    // Ages above threshold require manual underwriting. No instant quote.
    if (equipmentAge > maxAgeYears) return null;

    // Step 1: apply the 2% annual base rate.
    double annualPremium = equipmentValue * baseRate;

    // Step 2: apply the 15% fire suppression discount when applicable.
    if (hasFireSuppression) {
      annualPremium *= (1.0 - fireSuppressDiscount);
    }

    // Step 3: convert annual to monthly.
    return annualPremium / 12.0;
  }

  /// Returns the absolute monthly savings generated by the fire suppression
  /// discount, given the current [equipmentValue]. Returns 0 when ineligible.
  static double fireSavingsPerMonth(double equipmentValue) {
    final double annualFull = equipmentValue * baseRate;
    return (annualFull * fireSuppressDiscount) / 12;
  }
}